name: CI/CD to Docker Localhost

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Docker
        run: echo "${{ secrets.DOCKER_TOKEN }}" | docker login --username "${{ github.actor }}" --password-stdin localhost

      - name: Build Docker Image
        run: |
          docker buildx create --use
          docker buildx inspect
          docker buildx build -t localhost:5000/newbiedocker:latest .

      - name: Push Docker Image to Local Registry
        run: docker push localhost:5000/newbiedocker:latest

      - name: Deploy to Local Docker
        run: docker run -d -p 8080:80 localhost:5000/newbiedocker:latest
